name: Android Beta Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development # Specify the environment name
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          cd android && ./gradlew wrapper

      - name: Install fastlane
        run: |
          gem install bundler
          bundle install

      - name: Create Google Play credentials file
        run: |
          mkdir -p fastlane
          echo '${{ secrets.GOOGLE_PLAY_CREDENTIALS }}' > fastlane/google-play-credentials.json

      - name: Ensure clean git status
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git status
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: automated commit by GitHub Actions"
          fi

      - name: Run fastlane android beta
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: bundle exec fastlane android beta
